language: smalltalk
sudo: false
dist: bionic

notifications:
    email:
        on_success: never
        on_failure: always

before_install:
  - sudo apt install libvlc-dev libvlccore-dev
  - export PATH=$PATH:/usr/lib
  - whereis libvlc
  - ls -l /usr/lib/x86_64-linux-gnu/libvlc.so
  - whereis libvlccore
  - ls -l /usr/lib/x86_64-linux-gnu/libvlccore.so
  - ls  
  - pwd
addons:
  apt:
    update: true

os:
- linux

smalltalk:
  - Pharo64-8.0
