language: smalltalk
sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

before_install:
  - sudo apt-get -y install vlc

os:
- linux

smalltalk:
  - Pharo64-8.0
