language: smalltalk
dist: bionic

before_install:
  - . ci/before_install.sh
  - export PATH=$PATH:/usr/lib
  - ls -l `whereis libvlc | cut -d' ' -f2`
  - ls -l `whereis libvlccore | cut -d' ' -f2`

addons:
  apt:
    update: true
    packages:
      - libvlc-dev
      - libvlccore-dev
      - vlc

os:
- linux

smalltalk:
  - Pharo64-8.0
