language: smalltalk
dist: bionic

os:
- linux

before_install:
  - . ci/before_install.sh
  - export PATH=$PATH:/usr/lib
  - ls -l `whereis libvlc | cut -d' ' -f2`
  - ls -l `whereis libvlccore | cut -d' ' -f2`

addons:
  apt:
    update: true
    packages:
      - libvlc-dev
      - libvlccore-dev
      - vlc


smalltalk:
  - Pharo64-8.0
  - Pharo64-9.0

matrix:
  fast_finish: true
  allow_failures:
    - smalltalk: Pharo64-9.0
